language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - python2.7-dev

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cmake .
  - make
  - cd test
  - export PYTHON_PATH=/usr/include/python2.7
  - make && ./test.out